site_name: ATM Dokumentation
site_url: https://atm.node5.de

nav:
  - Startseite: index.md
  - Anforderungsdokumentation: requirements.md
  - Codedokumentation:
      - Ist-Dokumentation: codedocumentation/is-documentation.md
      - Delta-Dokumentation: codedocumentation/delta-documentation.md
  - Über das Team: about.md

theme:
  name: material

plugins:
  - search
  - with-pdf:
      author: Die Panzerknacker
      copyright: © 2022 Die Panzerknacker
      cover_title: ATM Dokumentation
      cover_subtitle: Die Panzerknacker
      toc_title: Inhaltsverzeichnis
      heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #two_columns_level: 3
      output_path: docs.pdf
